apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-seedusers
data:
  seedusers.ldif: |
{{- include (print .Template.BasePath "/_seedusers2.ldif.tpl") . | indent 4 }}  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
spec:
  ports:
    - port: 389
  selector:
    app: {{.Release.Name}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: osixia/openldap:1.1.10
          args: ["--loglevel", "debug"]
          volumeMounts:
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
            - name: {{.Release.Name}}-seedusers
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              value: "Example Inc."
            - name: LDAP_DOMAIN
              value: "{{.Values.OpenLdap.Domain}}"
            - name: LDAP_ADMIN_PASSWORD
              value: "{{.Values.OpenLdap.AdminPassword}}"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "false"
      volumes:
        - name: ldap-certs
          hostPath:
            path: "/data/ldap/certs"
        - name: {{.Release.Name}}-seedusers
          configMap:
            name: {{.Release.Name}}-seedusers

