apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: engine
  name: engine
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: engine
    spec:
      containers:
      - env:
        - name: DEBUG
        - name: LOG_LEVEL
          value: "INFO"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGO_DB
          value: dev
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_URL
          value: mongodb://cello-mongo:27017
        image: hyperledger/cello-engine
        name: cello-engine
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
